### ISSUE TITLE
PublicKey is not serializable

### ISSUE THREAD

**Issue by dhaavi** [rot256/pblind#2]
The current implementation of `PublicKey` only has private fields, making it impossible to make it, well, public.

Please export the fields or provide serialization functions, as is the case with `SecretKey`.

https://github.com/rot256/pblind/blob/c313473633f046b986e74b151a5d180ce1e27967/keys.go#L10-L13

Otherwise, the library is coming along well! Thanks!

**Comment by dhaavi** [comment]
I'm also more than happy to supply a PR for this. In this case I'd want to specify the format first.

What do you think about:
- Length of X, encoded as varint
- X.Bytes()
- Length of Y, encoded as varint
- Y.Bytes()

Including the length of both X and Y allows detection of obvious invalid public keys.

**Comment by rot256** [comment]
I recommend against rolling your own format, use `elliptic.MarshalCompressed(Pk.curve, Pk.x, Pk.y)` instead.

**Comment by dhaavi** [comment]
Ok, will do! Didn't know that existed - just saw you use .Bytes() for the secret key.
